###################################################################################
#                                                                                 #
#                                  Skyblock Core                                  #
#                                  by olliedean                                   #
#                                                                                 #
###################################################################################

# only enable this if you know what you're doing!
debug: false



###################################################################################
#                                                                                 #
#                                    Announcer                                    #
#                                                                                 #
###################################################################################

messages:
  - "&cThis is an example announcer message"
  - "&eDid you know blah blah blah"
  - "&eThis plugin was made by olliedean"